--[[ 
Coordinates for the default campaign of WH3. 
Used the 2 coordinates system of a physical image map and the logical map through the script_debug_activator mod whenever one clicks on a character (coordinates log is the logical coordinates on the map).

Things to understand: 
- ORDERED BY KNOWN ZONE
[ZONE]
- PROVINCE

Special buildings are maximum 2 per zone only. As such they are specially separated and assigned here once the mod configuration tool is in the workshop, make all this configurable.
--]]
-- Auto generated by algorithm in Jun 29, 2022.
-- Map: Realm Of Chaos
local roc_coordinates = {
     ["kislev"] = {
          -- Troll Country
          {284, 231},
          {328, 210},
          {243, 169},
          {243, 220},
          -- Northern Oblast
          {365, 134},
          {319, 169},
          {280, 180},
          -- River Lynsk: Erengrad
          {238, 145},
          {282, 137},
          -- Black Blood Pass
          {367, 218},
          -- The Cursed City: Praag
          {435, 196},
          -- River Urskoy: Kislev
          {439, 135},
          -- Eastern Oblast
          {518, 135},
          {463, 175},
          -- Dukhlys Forest
          {489, 198},
          {514, 178},
          {557, 221},
     },
     ["darklands"] = {
          -- Zorn Uzkul
          {682, 200},
          {766, 233},
          {734, 168},
          -- The Plain of Zharr
          {720, 144},
          {806, 165},
          {817, 210},
          -- The Blasted Wastes
          {762, 110},
          {776, 83},
          {792, 117},
          {858, 135},
          -- The Wolf Lands
          {848, 75},
          {823, 32},
          {881, 36},
          -- The Howling Wastes
          {873, 161},
          {866, 218},
          {933, 166},
          {941, 188},
          -- The Haunted Forest
          {956, 115},
          {1024, 162},
     },
     ["wordlsedgemountains"] = {
          -- The High Pass
          {692, 224},
          {603, 228},
          -- Worlds Edge Mountains
          {590, 133},
          -- Peak Pass
          {641, 107},
          {595, 78},
          -- Black Water
     },
     ["empire"] = {
          -- The Witch's Wood
          {98, 182},
          -- Wasteland
          {86, 126},
          {60, 140},
          {69, 97},
          {93, 77},
          -- Northern Grey Mountains
          -- Southern Grey Mountains
          {79, 33},
          -- Middenland
          {137, 121},
          {161, 97},
          {181, 111},
          -- Nordland
          {157, 182},
          {167, 150},
          {214, 131},
          -- Hochland
          {214, 56},
          {257, 45},
          {287, 63},
          -- Reikland
          {132, 53},
          {161, 41},
          {227, 32},
          -- Wissenland
          {350, 38},
          {355, 20},
          -- Talabecland
          {346, 55},
          -- Ostland
          {327, 137},
          {309, 113},
          {360, 107},
          {337, 88},
          -- Ostermark
          {437, 108},
          {429, 83},
          {472, 77},
          {513, 104},
          -- Stirland
          {381, 37},
          {426, 19},
          {434, 55},
          -- Sylvania
          {457, 18},
          {499, 23},
          {517, 61},
     },
     ["norsca"] = {
          -- Vanaheim Mountains
          {67, 457},
          {45, 432},
          {87, 378},
          -- Helspire Mountains
          {164, 381},
          {203, 332},
          {265, 336},
          -- Ice Tooth Mountains
          {129, 338},
          {136, 300},
          {163, 332},
          -- Trollheim Mountains
          {214, 276},
          {260, 252},
          -- Gianthome Mountains
          {292, 305},
          {328, 287},
          {388, 272},
          {474, 280},
          {520, 263},
          -- The Goromadny
          {582, 260},
          {618, 273},
     },
     ["mountainsofmourn"] = {
          -- Path to the East
          {733, 317},
          {768, 366},
          -- Gash Kadrak
          {800, 304},
          {820, 338},
          -- Mountains of Mourn
          {879, 338},
          -- Mist Gorge
          {945, 326},
          -- Wyrm Pass
          {1010, 330},
          {988, 281},
          -- Bone Road
          {863, 465},
          -- Ivory Road
          -- Ice Pass
          -- Ancient Giant Lands
     },
     ["cathay"] = {
          -- Imperial Road
          {1004, 664},
          {959, 656},
          {1058, 642},
          {1028, 631},
          -- Land of Stone and Steel
          {942, 632},
          {914, 560},
          {948, 579},
          {912, 584},
          -- Forests of the Moon
          {1042, 575},
          {1035, 603},
          -- Gunpowder Road
          {909, 516},
          {920, 491},
          {950, 521},
          -- Warpstone Desert
          {930, 461},
          {955, 454},
          {985, 484},
          -- Celestial Riverlands
          {1084, 579},
          {1094, 469},
          -- Wasteland of Jinshen
          {1040, 456},
          {981, 449},
          {1040, 456},
          -- Broken Lands of Tian Li
          {1059, 417},
     },
     ["chaoswastes"] = {
          -- The Shard Lands
          {105, 577},
          {139, 566},
          {247, 582},
          {244, 533},
          -- Northern Wastes
          {107, 520},
          {137, 477},
          {188, 435},
          {198, 487},
          {216, 515},
          -- The Eternal Lagoon
          {298, 544},
          {338, 524},
          {329, 471},
          -- Bloodfire Falls
          {274, 442},
          {303, 440},
          {338, 442},
          {273, 398},
          -- The Cold Mires
          {291, 372},
          {298, 412},
          -- Plain of Bone
          {409, 474},
          {446, 457},
          {491, 460},
          -- Plain of Illusions
          {442, 401},
          {392, 376},
          {389, 337},
          {436, 357},
          {486, 360},
          {524, 351},
          -- The Blood Marshes
          {487, 410},
          {553, 445},
          {565, 417},
          {552, 382},
          -- K'datha
          {619, 449},
          {605, 417},
          {642, 472},
          {680, 478},
          {741, 470},
          -- The Cliffs of Death
          {607, 320},
          {633, 313},
          -- Road of Skulls
          {677, 316},
          {678, 339},
          {716, 360},
          {679, 391},
          {723, 398},
          {733, 431},
          -- Road to Damnation
          {814, 420},
          {801, 462},
          {788, 490},
          {741, 470},
          -- Eastern Steppes
          {851, 517},
          {850, 572},
          -- The Red Wastes
          {888, 589},
          {862, 612},
          {895, 618},
          {894, 646},
     },
}

return roc_coordinates