return {
    "wh_main_anc_magic_standard_lichbone_pennant", 
    
    "wh_main_anc_armour_charmed_shield",
    "wh_main_anc_armour_enchanted_shield",
    "wh_main_anc_armour_gamblers_armour",
    "wh_main_anc_armour_shield_of_ptolos",
    "wh_main_anc_armour_spellshield",
    "wh_main_anc_armour_glittering_scales",
    "wh_main_anc_armour_tricksters_helm",
    "wh_main_anc_armour_armour_of_fortune",
    "wh_main_anc_armour_helm_of_discord",
    "wh_main_anc_armour_armour_of_destiny",

    "wh_main_anc_enchanted_item_ironcurse_icon",
    "wh_main_anc_enchanted_item_potion_of_strength",
    "wh_main_anc_enchanted_item_ruby_ring_of_ruin",
    "wh_main_anc_enchanted_item_the_terrifying_mask_of_eee",
    "wh_main_anc_enchanted_item_potion_of_toughness",
    "wh_main_anc_enchanted_item_healing_potion",
    "wh_main_anc_enchanted_item_the_other_tricksters_shard",
    "wh2_dlc15_anc_arcane_item_black_dragon_special",

    "wh_main_anc_talisman_dawnstone",
    "wh_main_anc_talisman_luckstone",
    "wh_main_anc_talisman_opal_amulet",
    "wh_main_anc_talisman_pidgeon_plucker_pendant",
    "wh_main_anc_talisman_talisman_of_protection",
    "wh_main_anc_talisman_talisman_of_endurance",
    "wh_main_anc_talisman_talisman_of_preservation", 
    
    "wh_main_anc_weapon_berserker_sword",
    "wh_main_anc_weapon_biting_blade",
    "wh_main_anc_weapon_gold_sigil_sword",
    "wh_main_anc_weapon_relic_sword",
    "wh_main_anc_weapon_shrieking_blade",
    "wh_main_anc_weapon_sword_of_might",
    "wh_main_anc_weapon_tormentor_sword",
    "wh_main_anc_weapon_fencers_blades",
    "wh_main_anc_weapon_sword_of_anti-heroes",
    "wh_main_anc_weapon_sword_of_strife",
    "wh_main_anc_weapon_sword_of_striking",
    "wh_main_anc_weapon_warrior_bane",
    "wh_main_anc_weapon_ogre_blade",
    "wh_main_anc_weapon_giant_blade",
    "wh_main_anc_weapon_obsidian_blade",
    
    "wh_main_anc_arcane_item_channelling_staff",
    "wh_main_anc_arcane_item_earthing_rod",
    "wh_main_anc_arcane_item_power_scroll",
    "wh_main_anc_arcane_item_power_stone",
    "wh_main_anc_arcane_item_scroll_of_shielding",
    "wh_main_anc_arcane_item_wand_of_jet",
    "wh_main_anc_arcane_item_power_stone",
    "wh_main_anc_arcane_item_sceptre_of_stability",
    "wh_main_anc_arcane_item_forbidden_rod",
    "wh_main_anc_arcane_item_book_of_ashur",
    "wh2_dlc13_anc_arcane_item_amplifier"
    
}