-- scm_motm
local caps = {
    -- Ogre Kingdoms
    {"hrothgul_gorgers", "special", 2},
    {"um_gnoblar_spider_riders_0", "core", 1},
    {"um_gnoblar_grillers", "core", 1},
    {"ogr_flamewarrior", "core", 1},
    {"um_kho_ogre_0", "core", 1},
    {"motm_jhared_feral_stegadon", "special", 2},
    {"motm_jhared_squig_explosive", "core", 1},
    {"um_gnoblar_spider_riders_1", "core", 1},
    {"motm_jhared_wolves", "special", 1},
    {"um_kho_ogre_2", "core", 1},
    {"um_gnoblar_grillers_ror", "core", 1},
    {"ogr_arachnarok_spider_0", "rare", 3},
    {"um_ogr_flamefang_cavalry", "special", 2},
    {"hrothgul_thundertusk_shrine", "rare", 2},
    {"um_ogr_treehammer_maneaters_02", "special", 2},
    {"motm_jhared_feral_wyvern", "special", 2},
    {"um_ogr_treehammer_maneaters_01", "special", 2},
    {"motm_gnoblar_scraplauncher_ror", "rare", 1},
    {"um_ogr_diver_02", "special", 2},
    {"ogr_lava_arachnarok_ror", "rare", 3},
    {"um_ogr_morg_ironguts_ror", "special", 1},
    {"ogr_arachnarok_spider_flinger", "rare", 3},
    {"motm_giant_spiders", "special", 1},
    {"motm_jhared_feral_rhinox", "special", 2},
    {"ogr_ice_mammoth_feral", "rare", 2},
    {"motm_boomhogg", "core", 1},
    {"motm_cyclop", "rare", 2},
    {"um_ogr_sea_rider", "special", 2},
    {"blautfang_warbeasts", "special", 1},
    {"um_ogr_dirty_shanks", "special", 2},
    {"ogr_flameeater_pistol", "special", 2},
    {"blaut_maneaters", "special", 2},
    {"um_ogr_treehammer_bulls_02", "core", 1},
    {"motm_ironblaster_ror", "rare", 1},
    {"fleshrender_hunters", "special", 2},
    {"ogr_hrothgul_yhetees_ironfists", "special", 2},
    {"motm_jhared_feral_carnosaur", "rare", 2},
    {"hkrul_boartusk_mammoth_ror", "rare", 3},
    {"motm_jhared_feral_cold_ones", "core", 1},
    {"hkrul_skraevold", "rare", 2},
    {"motm_jhared_feral_thundertusk", "rare", 2},
    {"um_ogr_skullflingers", "core", 1},
    {"motm_jhared_feral_stonehorn", "rare", 2},
    {"motm_jhared_feral_hydra", "rare", 2},
    {"um_ogr_old_funders_boys", "special", 1},
    {"motm_jhared_feral_mammoth", "rare", 2},
    {"motm_ogr_mon_stone_trolls_0", "special", 2},
    {"um_ogr_blackpowder", "rare", 2},
    {"lab_skv_rat_ogre_mutant", "special", 2},
    {"um_kho_ogre_1", "core", 1},
    {"motm_ogr_pit_fighters_cavalry", "special", 2},
    {"ogr_flame_spirits", "special", 2},
    {"wh3_main_ogr_inf_gnoblars_flingers", "core", 1},
    {"um_ogr_diver_01", "special", 2},
    {"gnoblar_spider_chariot", "special", 1},
    {"motm_jhared_feral_mournfang", "special", 2},
    {"motm_jhared_feral_ice_bears", "special", 2},
    {"um_ogr_flamegut", "special", 1},
    {"motm_beastclad_reavers", "special", 2},
    {"motm_ogr_pit_fighters", "special", 1},
    {"hunter_spider_chariot", "special", 1},
    {"ogr_flame_thrower", "special", 2},
    {"um_ogr_treehammer_bulls_01", "core", 1},
    {"blaut_maneaters_ror", "special", 2},
    {"motm_jhared_feral_manticore", "special", 1},
    {"lab_ogr_sabretusk", "special", 1},
    {"motm_jhared_feral_bears", "special", 1},
    {"lab_skv_brood_horror", "special", 1},
    {"fulg_irongut", "special", 2},
    {"um_ogr_manbiters", "special", 1},
    {"ogr_flameeater_hammer", "special", 2},
    {"lab_skv_hell_pit_abomination", "rare", 2},
    {"ogr_hrothgul_yhetees_great_weapon", "special", 2},
    {"lab_skv_rat_ogre", "special", 1},
    {"um_ogr_captain", "special", 2},
    {"um_ogr_blu", "rare", 2},
    {"um_gnoblar_spider_riders_ror", "core", 1},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end