-- cf-Ksl-units
local caps = {
    -- Kislev
    {"cf_ungol_warrior_drunk", "core"},
    {"cf_ungol_warrior_shield", "core"},
    {"cf_armoured_kossars_dual_swords", "core"},
    {"cf_go_emissary", "rare", 1},
    {"cf_salyak_priest", "rare", 1},
    {"cf_kvaskrovka_infantry", "core"},
    {"cf_praag_guards", "core"},
    {"cf_war_altar_of_ursun", "special", 1},
    {"cf_akshina_ambushers_dual_axes", "rare", 1},
    {"cf_akshina_ambushers_great_axes", "rare", 1},
    {"cf_chekist", "special", 1},
    {"cf_ice_guard_glaive", "rare", 1},
    {"cf_ice_guard_dual_sword", "rare", 1},
    {"cf_ice_guard_shield", "rare", 1},
    {"cf_kurgan_brute", "special", 2},
    {"cf_tzar_guard_2", "special", 2},
    {"cf_boyar_guards", "special", 2},
    {"cf_cultist_leader", "special", 3},
    {"cf_gryphon_legion_halberds", "special", 2},
    {"cf_royal_bokha_palace_guard", "special", 2},
    {"cf_royal_kreml_guard", "special", 2},
    {"cf_tors_lighting_strike", "rare", 1},
    {"cf_ursuns_claws", "rare", 1},
    {"cf_streltsi_pistol_bardiche", "core"},
    {"cf_streltsi_snipers", "core"},
    {"cf_akshina_ambushers_javelins", "rare", 1},
    {"cf_streltsi_blunderbuss", "core"},
    {"cf_gryphon_legion_archers", "special", 1},
    {"cf_sibyrian_hunters", "special", 1},
    {"cf_mounted_cossacks", "core"},
    {"cf_mounted_huns", "core"},
    {"cf_light_war_sled_melee", "special", 2},
    {"cf_tzar_guard_cav", "special", 2},
    {"cf_heavy_war_sled_melee", "special", 3},
    {"cf_ice_guard_cav_glaive", "rare", 1},
    {"cf_winged_lancers_tor", "rare", 1},
    {"cf_black_bear_riders", "special", 3},
    {"cf_ice_guard_bear_riders", "rare", 1},
    {"cf_ice_guard_cav_pegasus", "special", 3},
    {"cf_gryphon_legion_knights", "special", 3},
    {"cf_dazh_hearth_blades_cav", "rare", 1},
    {"cf_black_bear_riders_ror", "rare", 1},
    {"cf_horseback_streltsi_rifle", "core"},
    {"cf_horseback_streltsi_blunderbuss", "core"},
    {"cf_horseback_streltsi_pistols", "core"},
    {"cf_akshina_javelin_cavalry", "rare", 1},
    {"cf_ice_guard_missile_cav", "rare", 1},
    {"cf_throwing_axe_cavalry", "special", 1},
    {"cf_kvaskrovka_cavalry", "special", 1},
    {"cf_light_war_sled_blunderbuss", "special", 2},
    {"cf_light_war_sled_kvaskrovka", "special", 2},
    {"cf_light_war_sled_ice_guard", "special", 2},
    {"cf_gryphon_legion_horse_archers", "special", 3},
    {"cf_heavy_war_sled_blunderbuss", "special", 3},
    {"cf_heavy_war_sled_kvaskrovka", "special", 3},
    {"cf_heavy_war_sled_ice_guard", "special", 3},
    {"cf_light_war_sled_blunderbuss_ror", "rare", 2},
    {"cf_heavy_war_sled_blunderbuss_ror", "rare", 2},
    {"cf_feral_elk", "core"},
    {"cf_giant_spider_frost", "special", 1},
    {"cf_akshina_scout_hawks", "special", 1},
    {"cf_armoured_black_bear", "special", 2},
    {"cf_armoured_brown_bear", "special", 2},
    {"cf_armoured_ice_bear", "special", 2},
    {"cf_ancient_widow", "rare", 2},
    {"cf_dazh_phoenix", "rare", 3},
    {"cf_tor_phoenix", "rare", 3},
    {"cf_frostheart_phoenix", "rare", 3},
    {"cf_erengrad_cannon", "special", 2},
    {"cf_ksl_axe_thrower", "special", 2},
    {"cf_praag_cannons", "special", 2},
    {"wh3_main_ksl_veh_little_grom_mortar_0", "rare", 2},
    {"wh3_main_ksl_veh_little_grom_rockets_0", "rare", 2},
    {"cf_big_brass_cannon", "rare", 2},
    {"cf_dazh_fire_rockets", "rare", 2},
    {"wh3_main_ksl_veh_little_grom_ice", "rare", 2},
    {"cf_tor_mortar", "rare", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end