-- Zerooz_All_Units
-- Unit keys are different than the ones in main_units_table.
local caps = {
    -- Beastmen
    {"bst_inf_tzaangors_archer", "special", 1},
    {"bst_inf_centigors_great_axe_mnur", "rare", 1},
    {"bst_inf_centigors_great_sword", "rare", 1},
    {"bst_inf_centigors_throwing_axes_mnur", "rare", 1},
    -- Bretonnia
    {"haven_praetorian", "special", 1},
    {"haven_squire", "special", 1},
    {"haven_judge", "special", 1},
    {"haven_crossbowman", "core"},
    {"haven_paladin", "special", 2},
    {"haven_sunrider", "special", 2},
    {"haven_royal_hippogryph", "special", 2},
    {"haven_arcangel", "special", 2},
    -- Dark Elves
    {"def_inf_daughters_of_khaine", "core"},
    {"def_inf_blood_sisters", "special", 1},
    {"def_inf_khaine_tracker", "special", 2},
    {"def_cav_shadow_maiden", "core"},
    {"def_mon_shadow_lifetaker", "rare", 1},
    -- Grand Cathay
    {"cth_inf_gouxiang", "core"},
    {"cth_inf_jade_warrior_stick", "core"},
    {"cth_inf_jade_warrior_great_sword", "core"},
    {"cth_inf_jade_warrior_halberd_shield", "core"},
    {"cth_inf_dragon_guard_fighter", "rare", 1},
    {"cth_inf_dual_hammer", "rare", 1},
    {"cth_inf_dual_jian", "rare", 1},
    {"cth_inf_nangao_firework_trops", "rare", 1},
    {"cth_inf_god_guard_fighter", "rare", 2},
    {"cth_inf_dragon_tiger_guard", "rare", 2},
    {"cth_inf_bian", "rare", 2},
    {"cth_inf_pioneer_scouts", "core"},
    {"cth_inf_fire_explosion_crossbow", "core"},
    {"cth_thunder_attack_gunners", "special", 1},
    {"cth_inf_thunderbolt_gunners", "rare", 1},
    {"cth_inf_moon_yinyang_maiden", "special", 1},
    {"cth_cav_nangao_fire_lance", "special", 1},
    {"cth_cav_celestial_mighty_axe_guard", "special", 2},
    {"cth_cav_xiaoguojun", "rare", 2},
    {"cth_inf_onyx_armored_crowmen", "special", 1},
    {"cth_mon_terracotta_sentinels_small", "rare", 2},
    {"cth_mon_terracotta_sentinel_watcher", "rare", 2},
    {"cth_mon_celestial_lion_rider", "rare", 3},    
    {"cth_cav_jade_crossbow_rider", "special", 1},
    {"cth_cav_celestial_crossbow_rider", "rare", 1},
    {"cth_cav_jade_longma_crassbow_rider", "rare", 2},
    {"cth_veh_war_compass_1", "rare", 1},
    {"cth_sky_junk_cannon", "special", 3},
    {"cth_veh_sky_boat", "special", 3},
    {"cth_veh_sky_ark", "rare", 2},
    -- High Elves
    {"hef_inf_guard_of_eternal_02", "special", 1},
    {"hef_inf_dual_axe_of_chrace", "special", 1},
    {"hef_inf_guard_of_eternal_03", "special", 1},
    {"hef_inf_guardian_of_hoeth", "special", 2},
    {"hef_inf_cothique_abyss_observers", "special", 2},
    {"hef_inf_sword_master_of_phenix", "special", 3},
    {"hef_inf_pride_of_the_white_lions", "special", 3},
    {"hef_inf_the_light_of_yvresse", "special", 3},
    {"hef_inf_hunter_of_chrace", "special", 1},
    {"hef_inf_scouts_of_eternal", "rare", 1},
    {"hef_inf_sea_master", "special", 2},
    {"hef_cav_corsair_mariners", "special", 2},
    {"hef_cav_caledor_dragon_knight", "rare", 1},
    {"hef_cav_strike_of_eternal", "rare", 1},
    {"hef_cav_rider_of_eternal", "rare", 1},
    {"hef_cav_cothique_shore_watchers", "special", 2},
    {"hef_cav_skyraider_of_eternal", "rare", 1},
    {"hef_cav_sister_of_eternal", "special", 3},
    {"hef_mon_son_of_rahagra", "special", 1},
    {"hef_cav_dragon_knight", "rare", 3},
    {"hef_inf_mage_of_hoeth", "rare", 2},
    {"hef_cav_cothique_deepsea_marauders", "special", 3},
    {"hef_inf_brave_guardians", "special", 2},
    {"hef_inf_brave_blademen", "special", 3},
    {"hef_inf_brave_acher", "special", 2},
    -- Ogres
    {"ogr_gnoblar_dual_sword", "core"},
    {"ogr_inf_ironguts_cth_0", "core"},
    {"ogr_inf_ironguts_cth_1", "core"},
    {"ogr_goblin_archers", "core"},
    {"ogr_leadbelchers_longrange", "special", 2},
    {"ogr_leadbelchers_flame", "special", 2},
    {"ogr_cav_goblin_wolf_riders_archers", "core"},
    {"ogr_goblin_wolf_rider_spear", "core"},
    {"ogr_veh_rhinox_draft", "special", 1},
    {"ogr_mon_stonehorn_wild", "rare", 1},
    {"ogr_inf_eshin_maneater", "special", 3},
    {"ogr_inf_orger_hunter", "special", 1},
    -- Empire
    {"emp_inf_nordland_seahawks", "core"},
    {"emp_inf_vengeful_blades", "core"},
    {"emp_inf_reiksguard", "core"},
    {"emp_inf_sigmar_attaker", "special", 1},
    {"emp_inf_sigmar_guards", "special", 1},
    {"emp_inf_sons_of_the_reik", "special", 2},
    {"emp_inf_nordland_ultimate_warrior", "special", 3},
    {"emp_inf_sigmar_destroyer", "special", 2},
    {"emp_inf_free_hunting_corps", "core"},
    {"emp_inf_nuln_ironsides_heavy_armor", "special", 2},
    {"emp_inf_nuln_ironsides_repeaters", "special", 2},
    {"emp_inf_ostland_salamanders", "rare", 1},
    {"emp_inf_dark_angel", "rare", 1},
    {"emp_inf_sigmar_marksmen", "special", 2},
    {"emp_cav_knight_of_white_wolf", "special", 2},
    {"emp_cav_long_sword_demigryph_knights", "special", 3},
    {"emp_cav_gryph_knights", "rare", 1},
    {"emp_cav_knight_of_the_raven", "special", 2},
    {"emp_cav_dual_pistols_demigryph_knights", "special", 3},
    {"emp_mon_eagles_summoned", "special", 1},
    {"emp_inf_nuln_ironsides_morr_repeaters", "special", 2},
    {"emp_inf_sterntower_marksmen", "core"},
    {"emp_inf_bronzeballs", "special", 1},
    -- Nurgle
    {"nur_inf_plague_cultist", "core"},
    {"chs_inf_death_guard_mnur", "rare", 1},
    {"nur_cav_plague_cultist", "core"},
    {"chs_cav_chaos_knights_mnur_axe", "special", 2},
    {"chs_cav_death_reaper_mnur", "special", 2},
    {"chs_inf_chaos_marauders_mnur_throwing_axes", "core"},
    {"nur_inf_plague_ogres_cannon", "rare", 2},
    {"nur_mon_plague_toads_armoured", "special", 1},
    {"nur_inf_centigors_great_axe", "rare", 1},
    {"nur_inf_centigors_throwing_axes", "rare", 1}, 
    -- Tzeentch
    {"tze_inf_tzaangors_archer", "special", 1},
    {"tze_inf_centigors_great_sword", "rare", 1},
    {"tza_inf_change_of_thousand_sons", "special", 3},
    {"tze_cav_doom_tzaangors_archer", "special", 2},
    {"tza_veh_doom_chariot", "rare", 1},
    {"tze_cav_doom_tzaangors", "special", 2},
    -- Wood Elves
    {"wef_cav_spears_of_orion", "special", 3},
    {"wef_mon_durthus_wargrove", "rare", 3},
    {"wef_inf_twilight_guard", "special", 3},
    {"wef_mon_treemen_acher", "special", 3},
    {"wef_inf_talsyn_hawks", "special", 2},
    {"wef_cav_great_stag_rangers", "special", 3},
    {"wef_mon_treemen_acher_evil", "special", 3},
    {"wef_inf_war_druid_human", "special", 3},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end