-- Trajanns_Khorne_Compilation
local caps = {
    -- Chaos Dwarfs
    {"traj_khazdrakk_ror", "rare", 1},
    {"traj_kho_thunderbarge", "rare", 3},
    -- Orcs
    {"traj_skorrog_ror", "special", 2},
    -- Khorne
    {"traj_kho_skink_greataxe", "core"},
    {"traj_kho_skink_greataxe_ror", "special", 1},
    {"traj_kho_irongut_infantry_dual", "special", 1},
    {"traj_kho_irongut_infantry_great", "special", 1},
    {"traj_blood_dragon_celestial_guard_ror", "special", 2},
    {"traj_kho_dwarf_infernal_ironsworn_great", "special", 2},
    {"traj_kho_dwarf_infernal_ironsworn_dual", "special", 2},
    {"traj_gormak_ror", "special", 2},
    {"traj_kho_skink_cohort", "core"},
    {"traj_kho_skink_skirmish", "core"},
    {"traj_kho_dwarf_infernal_ironsworn_blood_raker", "special", 2},
    {"traj_kho_dwarf_infernal_ironsworn_flame_cannon", "special", 2},
    {"traj_kho_dwarf_infernal_ironsworn_sniper_fireglaives", "special", 2},
    {"traj_kho_dwarf_infernal_ironsworn_heavy_fireglaives", "special", 2},
    {"traj_khazdrakk_ror", "special", 2},
    {"traj_kho_razordon_small", "special", 2},
    {"traj_kho_terradon", "special", 2},
    {"traj_kho_salamander_small", "special", 2},
    {"traj_kho_razordon_ancient", "special", 2},
    {"traj_kho_salamander_small_ror", "special", 2},
    {"traj_kho_terradon_ror", "special", 2},
    {"traj_kho_bastiladon_engine", "special", 3},
    {"traj_kho_razordon_ancient_ror", "rare", 3},
    {"traj_kho_bastiladon_engine_ror", "rare", 3},
    {"traj_kho_skink_riders", "special", 1},
    {"traj_kho_forsaken_rider", "special", 1},
    {"traj_kho_ripperdactyl", "special", 2},
    {"traj_hespia_ror", "special", 1},
    {"traj_kho_khornate_guard_riders", "special", 3},
    {"traj_kho_ripperdactyl_ror", "rare", 2},
    {"traj_blood_dragon_longma_ror", "rare", 2},
    {"traj_castellan_skullcrusher", "rare", 2},
    {"traj_kho_things", "special", 2},
    {"traj_kho_kroxigor_sacred", "special", 2},
    {"traj_kho_bastiladon_revive", "special", 3},
    {"traj_khornataur_shield", "special", 3},
    {"traj_kho_cockatrice", "rare", 2},
    {"traj_kho_giant", "rare", 2},
    {"traj_kho_cygor", "rare", 3},
    {"traj_kho_frost_wyrm", "rare", 2},
    {"traj_kho_jabberslythe", "rare", 3},
    {"traj_kho_coatl", "rare", 3},
    {"traj_kho_elemental", "rare", 3},
    {"traj_kho_elemental_bear", "rare", 3},
    {"traj_kho_mutalith", "rare", 3},
    {"traj_kho_toad_dragon", "rare", 3},
    {"traj_kho_steam_tank", "rare", 3},
    {"eku_thundertusk", "rare", 3},
    {"eku_colossal_squig", "rare", 2},
    {"zkc_tomb_guard_bow", "core", 1},
    {"traj_kho_khorngor_great", "special", 1},
    {"eku_rotting_leviathan", "rare", 3},
    {"eku_heavy_war_sled", "special", 3},
    {"zkc_tomb_guard_swords", "core", 1},
    {"zkc_sepulchral", "special", 2},
    {"eku_juggernaught_chariot", "special", 2},
    {"eku_arachnarok_spider", "rare", 3},
    {"zkc_ushabti_bow", "special", 2},
    {"eku_dragon_princes_mounted", "special", 2},
    {"zkc_bone_giant", "rare", 3},
    {"traj_kho_skink_skirmish_ror", "special", 1},
    {"traj_kho_khorngor_dual", "special", 1},
    {"eku_treeman", "rare", 3},
    {"zkc_tomb_guard", "core", 1},
    -- Beastmen
    {"traj_khorgoth_minotaur_ror", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end